### PR TITLE
fix hydration error

### PR DESCRIPTION
**Pull request by NicoZweifel**
## Summary
Fixes Hydration errors described in #258

This is just to demonstrate for now and should probably be improved a bit more, especially the component.
Regarding the pop-in of code blocks, it is caused by hooks, you can check by replacing the `CodeBlock` with `CodeBlock: 'code'` in `\mint\client\src\components\index.ts` and the pop-in will disapear.

## Test Plan

Tested locally, could not find any visual changes. One issue can be missing bottom margin when using `<span>` instead of `<p>`, but it usually only happens for pure text and in this case `<p>` is still used.

I checked normal text, Accordions, Cards and CodeBlocks and couldn't find an issue there so far.

### CODE REVIEW

**Review by tobias-mintlify — COMMENTED** [review]
The missing margin you encountered is because Tailwind Typography, a plugin we use, only applies margins to headers and paragraphs. We also need to keep the parent `p` tag for accessibility purposes.

Do you have any sources I could read to learn why MDX doesn't like other tags nested inside `p`? I generally understand we aren't supposed to nest things inside `p` but I thought `code` was one of the accepted tags similar to `span`.

**Comment by NicoZweifel** [comment]
The error itself is just related to next.js throwing this error when there are invalid elements.

As far as I understand it is because of the `pre` blocks because they are block elements.
If we managed to only place `code` when there is already a `p` element the error will disapear.
Maybe this is a better solution but I am not sure right now how to go about that. Could try by messing with the MDXComponents in another way.

**Comment by NicoZweifel** [comment]
found this: 
https://stackoverflow.com/questions/5371787/can-i-have-a-pre-tag-inside-a-p-tag-in-tumblr
https://webmasters.stackexchange.com/questions/18150/html-should-code-be-placed-within-a-paragraph

**Comment by NicoZweifel** [comment]
It turns out that the fix from [here ](https://github.com/mintlify/components/pull/39) with the Code Block actually also fixes the Hydration Error, there is no more extra `<pre>` element generated now that it is beeing rendered on the server.

**Comment by NicoZweifel** [comment]
Leaving this PR/Issue for when the new package version is released.

**Comment by NicoZweifel** [comment]
have this result now, no more warnings/errors and no pop in, but the margin isn't consistent, so I don't think we can use this yet:
image

**Comment by NicoZweifel** [comment]
The Error in the starter Template can be removed by adding a newline after the text blocks, which will cause the paragraph to close before the calloutTemplates. No errors/warnings like this anymore and no margin issues either on local setup with this starter template.
https://github.com/mintlify/starter/pull/2

**Review by tobias-mintlify — APPROVED** [review]
I'm going to merge because the PR is only adding a type, but hydration errors can still occur if the user adds callouts without a blank line right?

**Comment by NicoZweifel** [comment]
Yea it can occur if a user writes any block component without leaving a blank line in between the text. But we can track that in the issue, closing is fine with me 👍

**Pull request merged**
