### PR TITLE
Get all urls for sitemap

### PR DESCRIPTION
**Pull request by tobias-mintlify**
## Summary

Generates the sitemap using the new navigation and hosting location endpoints. This cannot be shipped until the new endpoints are live.

## Test Plan

Visit any multitenant site in development and add `/sitemap.xml` to the end. Revalidation will be sorted out in a separate PR.

## Future Work

robots.txt should disallow hidden pages. We can merge that separately.

### CODE REVIEW

**Review by hahnbeelee — CHANGES_REQUESTED** [review]
I don't think this comma is supposed to be here. 🤨 
CleanShot 2023-02-28 at 15 12 49

In comparison, look at this sitemap:
CleanShot 2023-02-28 at 15 13 34

**Comment by hahnbeelee** [comment]
@tobias-mintlify If we're figuring out revalidation separately what will be the current behavior? The sitemap will always refresh when someone hits it? or never refresh?

**Comment by tobias-mintlify** [comment]
The current behaviour is to revalidate when the entire project is deployed.

**Comment by hahnbeelee** [comment]
I know you said that `robots.txt` isn't done here but just wanted to let u kno I think ur missing an await somewhere.
CleanShot 2023-02-28 at 15 21 18

**Comment by tobias-mintlify** [comment]
Oops I made a small tweak after I was done all my testing, I'll fix that right now.

**Review by hahnbeelee — APPROVED** [review]

**Pull request merged**
